# generic settings
main_username: jonas
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"
timezone: Europe/Stockholm

ansible_sudo_pass: "{{ vault_default_sudo_pass }}"

appdata_path: /opt/appdata
mount_dir: /mnt/drives
storage_dir: /mnt/storage

nfs_share: /srv/storage

docker_data_dir: appdata
docker_puid: "{{ main_username }}"
docker_pgid: "{{ main_groupname }}"
docker_timezone: Europe/Stockholm
