- name: Install linux-modules-extra for the current kernel version
  apt:
    name: "linux-modules-extra-{{ ansible_kernel }}"
    state: latest
  register: install_modules

- name: Reboot if linux-modules-extra was installed or updated
  reboot:
    msg: "Rebooting after installing linux-modules-extra"
    connect_timeout: 5
    reboot_timeout: 600
  when: install_modules.changed

- name: install needed packages
  become: true
  apt:
    name:
      - cifs-utils
      - locales
    state: latest

- name: Generate UTF-8 locale (Debian/Ubuntu)
  become: true
  command: locale-gen en_US.UTF-8

- name: Get home directory of the user running Ansible
  ansible.builtin.set_fact:
    user_home_directory: "{{ lookup('env', 'HOME') }}"

- name: Create CIFS password file in user's home directory
  ansible.builtin.lineinfile:
    path: "{{ user_home_directory }}/{{ credentials_file }}"
    line: |
      username={{ smb_share_username }}
      password={{ smb_share_password }}
    create: yes
    state: present

- name: Ensure mount point exists
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory

- name: Mount SMB share
  ansible.builtin.mount:
    path: "{{ mount_point }}"
    src: "{{ smb_share_path }}"
    fstype: cifs
    opts: "credentials={{ user_home_directory }}/{{ credentials_file }},iocharset=utf8,sec=ntlmssp,uid={{ mount_uid }},gid={{ mount_gid }},vers=3.0"
    state: mounted
