- name: update all packages
  become: true
  package:
    name: '*'
    state: latest
    autoremove: true

- name: remove ubuntu motd spam
  become: true
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 80-livepatch
    - 95-hwe-eol
    - 10-help-text
  when: ansible_distribution == 'Ubuntu'

- name: Put public key in authorized_keys of remotes
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_path }}') }}"
