- name: Find all docker templates
  find:
    paths: "{{ docker_compose_dir }}"
    patterns: "*.yml"
  register: existing_docker_templates

- name: Delete all existing templates
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ existing_docker_templates['files'] }}"

- name: Deploy compose templates
  template:
    src: ../templates/compose/{{ item }}.yml
    dest: "{{ docker_compose_dir }}/{{ item }}.yml"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "0640"
  loop: "{{ docker_templates }}"

- name: Deploy extra files for compose files
  template:
    src: ../templates/extra-files/{{ item }}
    dest: "{{ docker_compose_dir }}/{{ item }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "0640"
  loop: 
    - unifi-init-mongo.js 

- name: Start containers
  command: "{{ docker_script_dir }}/start.sh"
