version: "3.8"

services:
  my-dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-dev-container
    command: zsh
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh:/home/developer/.ssh:ro
      - ~/repo:/home/developer/repo
      - ~/.kube/config:/home/developer/.kube/config
