apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy-downloader
  namespace: actions-runner-system
spec:
  replicas: 3
  template:
    spec:
      repository: josmase/downloader