docker_compose_dir: /opt/docker
script_dir: "{{ docker_compose_dir }}/scripts"

docker_templates:
  - emby
  - grafana
  - home-assistant
  - influxdb
  - kitana
  - ombi
  - pihole
  - plex
  - swag
  - tautulli
  - telegraf
  - unifi
  - vpn
  - jellyfin
  - tdarr
  - wireguard

script_templates:
  - common
  - down
  - maintenance
  - start
  - update

timers:
  - maintenance

timer_dir: /etc/systemd/system/
