docker_compose_dir: /opt/docker
script_dir: "{{ docker_compose_dir }}/scripts"

script_templates:
  - common
  - down
  - maintenance
  - start
  - update

timers:
  - maintenance

timer_dir: /etc/systemd/system/
