---
# Setup Kubernetes configuration
- name: Ensure .kube directory exists
  file:
    path: "{{ kubernetes_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Fetch Kubernetes config from first master node
  ansible.builtin.fetch:
    src: "/home/{{ kubernetes_master_user }}/.kube/config"
    dest: "{{ kubernetes_config_dir }}/config"
    flat: yes
  delegate_to: "{{ kubernetes_master_host }}"
  become: false
  when: kubernetes_master_host != None and kubernetes_master_user != None

- name: Set permissions on Kubernetes config
  ansible.builtin.file:
    path: "{{ kubernetes_config_dir }}/config"
    mode: "{{ kubernetes_config_mode }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
