version: "3.7"
services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/homeassistant:/config"
    restart: always
  zwave:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwave
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
      - SESSION_SECRET=ccd3fc23c7e9dafc5e8b8fdd5a621dab
    volumes:
      - "{{ appdata_path }}/zwave:/usr/src/app/store"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    ports:
      - 8091:8091
