version: "3.7"
services:
  emby:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/jellyfin:/config"
      - "{{ storage_dir }}/files/series:/data/tvshows"
      - "{{ storage_dir }}/files/movies:/data/movies"
    restart: always
