version: "3.7"
services:
  kitana:
    image: pannal/kitana
    container_name: kitana
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/kitana:/app/data"
    ports:
      - 31337:31337
    restart: always
