version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/plex:/config"
      - /tmp/transcode/plex:/transcode
      - "{{ storage_dir }}/files/movies:/movies"
      - "{{ storage_dir }}/files/series:/tv"
    network_mode: host
    restart: always
