version: "3.7"
services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - GROUPID={{ main_gid }}
      - USERID={{ main_uid }}
      - TZ={{ timezone }}
    network_mode: host
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - "{{ storage_dir }}/files:/mnt/files:z"
      - "{{ appdata_path }}:/mnt/appdata:z"
    command: '-s "Files;/mnt/files;yes;no;no;bob" -s "Appdata;/mnt/appdata;yes;no;no;bob" -u "bob;bobspasswd;{{ main_uid }};jonas;{{ main_gid }}" -p -n'