version: "3.7"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/tautulli:/config"
      - "{{ appdata_path }}/plex/Library/Application Support/Plex Media Server/Logs/:/logs"
    ports:
      - 8181:8181
    restart: always
