- name: remove ubuntu motd spam
  become: true
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 80-livepatch
    - 95-hwe-eol
    - 10-help-text
  when: ansible_distribution == 'Ubuntu'

- name: Install all packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present

- name: generate SSH key "{{ ssh_key_filename }}"
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_filename }}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Put public key in authorized_keys of remotes
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_path }}') }}"

- name: Disable that BEEP!
  # unsetopt BEEP for all beeps
  lineinfile:
    line: unsetopt LIST_BEEP
    path: ~/.zshrc
    state: present
    create: yes
