services:
  influxdb:
    image: {{ docker_registry_domain }}/influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=media-server
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=90d
      - PUID={{ docker_puid }}
      - GUID={{ docker_guid }}
      - TZ={{ timezone }}
    ports:
      -  8083:8083
      -  8086:8086
    volumes:
      - "{{ docker_data_dir }}/influxdb/data:/var/lib/influxdb2"
      - "{{ docker_data_dir }}/influxdb/config:/etc/influxdb2"
    restart: always
