services:
  jellyfin:
    image: {{ docker_registry_domain }}/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/jellyfin:/config"
      - "{{ docker_storage_dir }}/files/:{{ docker_storage_dir }}/files/"
    ports:
      - 8096:8096
    restart: always
