services:
  ombi:
    image: {{ docker_registry_domain }}/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/ombi:/config"
    restart: always
