---
- name: Reload systemd
  systemd:
    daemon-reload: true

- name: Restart unifi_os_server
  systemd:
    name: "{{ unifi_os_server_service_name }}"
    state: restarted
    enabled: true

- name: Stop unifi_os_server
  systemd:
    name: "{{ unifi_os_server_service_name }}"
    state: stopped