version: "3.7"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/ombi:/config"
    restart: always
