version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/plex:/config"
      - "{{ storage_dir }}/files/movies:/movies"
      - "{{ storage_dir }}/files/series:/series"
      - "{{ storage_dir }}/files/photos:/photos"
    restart: always
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
