version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/plex:/config"
      - "{{ storage_dir }}/files/movies:/movies"
      - "{{ storage_dir }}/files/series:/series"
      - "{{ storage_dir }}/files/photos:/photos"
      - "{{ storage_dir }}/files/plex/transcode:/config/transcode"
      - "{{ storage_dir }}/files/plex/tmp:/tmp"
    restart: always
    network_mode: host
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp

  kitana:
    image: pannal/kitana
    container_name: kitana
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/kitana:/app/data"
    ports:
      - 31337:31337
    restart: always
    
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/tautulli:/config"
      - "{{ appdata_path }}/plex/Library/Application Support/Plex Media Server/Logs/:/logs"
    ports:
      - 8181:8181
    restart: always
