---
dependencies: []

galaxy_info:
  author: josmase
  description: Installs and configures MJPG-Streamer for webcam streaming
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - mjpg-streamer
    - webcam
    - streaming
    - 3dprinting