---
galaxy_info:
  author: your_name
  description: Install and build mjpg-streamer from source
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
