apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../bases/certificate
  - traefik-dashboard
  - downloader
  - container-registry
  - cloudflare-ddns
  - it-tools
