# generic settings
main_username: ubuntu
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"
timezone: Europe/Stockholm

ansible_sudo_pass: "{{ vault_default_sudo_pass }}"

email: "{{ vault_email }}"

local_domain: "{{ vault_local_domain }}"
storage_domain: "storage.{{ local_domain }}"

appdata_dir: /opt/appdata
storage_dir: /mnt/storage

docker_storage_dir: "{{ storage_dir }}"
docker_data_dir: "{{ appdata_dir }}"
docker_puid: "{{ main_uid }}"
docker_pgid: "{{ main_gid }}"
docker_timezone: Europe/Stockholm
docker_registry_domain: docker.io
docker_registry_user: "{{ vault_docker_registry_user }}"
docker_registry_password: "{{ vault_docker_registry_password }}"

docker_compose_dir: /opt/docker
docker_script_dir: "{{ docker_compose_dir }}/scripts"

script_templates:
  - common
  - stop
  - maintenance
  - start
  - update
  - staleFileHandleHandler

timers:
  - maintenance
  - staleFileHandleHandler

timer_dir: /etc/systemd/system/
