# generic settings
main_username: ubuntu
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"
timezone: Europe/Stockholm

ansible_sudo_pass: "{{ vault_default_sudo_pass }}"

email: "{{ vault_email }}"

local_domain: "{{ vault_local_domain }}"
media_server_domain: "media.{{ local_domain }}"

appdata_path: /opt/appdata
mount_dir: /mnt/drives
storage_dir: /mnt/storage

nfs_share: /srv/storage

docker_data_dir: appdata
docker_puid: "{{ main_username }}"
docker_pgid: "{{ main_groupname }}"
docker_timezone: Europe/Stockholm
docker_registry_domain: docker.io
docker_registry_user: "{{ vault_docker_registry_user }}"
docker_registry_password: "{{ vault_docker_registry_password }}"
