ansible_sudo_pass: "{{ vault_hemmas_password }}"
main_username: hemmas
main_groupname: "{{ main_username }}"

docker_templates:
  - home-assistant
  - unifi
  - vpn
  - jellyfin

maintenance_calendar: "*-*-* 04:00:00"

movies_dir: "{{ docker_storage_dir }}/files/movies"
series_dir: "{{ docker_storage_dir }}/files/series"

sonarr_api_key: "{{ vault_sonarr_api_key }}"
radarr_api_key: "{{ vault_radarr_api_key }}"

docker_registry_domain: "docker.io"
