- name: install nfs-utils
  apt: 
    name: nfs-utils 
    state: latest

- name: enable rpcbind nfslock nfs
  service:
    name: "{{ item }}"
    enabled: yes
    with_items:
    - rpcbind
    - nfslock
    - nfs

- name: Copy exports file.
  template:
    src: ../templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: NFS apply change configrue
  shell: systemctl reload nfs;exportfs -a