- name: install nfs-utils
  become: true
  apt: 
    name: nfs-kernel-server 
    state: latest

- name: Copy exports file.
  become: true
  template:
    src: ../templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: NFS apply change configrue
  become: true
  shell: exportfs -a && systemctl restart nfs-kernel-server