- name: install nfs-utils
  become: true
  apt: 
    name: nfs-utils
    state: latest

- name: Copy exports file.
  become: true
  template:
    src: ../templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Bind storage to nfs exports
  become: true
  ansible.posix.mount:
    state: mounted
    path: "/srv/nfs4/{{ item }}"
    src: "{{ merger_fs_mnt_dest }}/{{ item }}"
    fstype: none
    opts: bind
  loop: "{{ exported_shares }}"

- name: Start and Enable nfs-server
  become: true
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    daemon-reload: yes

- name: NFS apply change configrue
  become: true
  shell: exportfs -arv

- name: Allow nfs4 port
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "2049"
    jump: ACCEPT