- name: Install packages
  become: true
  apt:
    name: git
    state: present

- name: Create compile dir
  become: true
  file:
    path: "{{ snapraid_compile_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  
- name: Clone install script
  git:
    repo: 'https://github.com/IronicBadger/docker-snapraid'
    dest: "{{ snapraid_compile_dir }}"
    force: yes

- name: Make build script executable
  file:
    dest: "{{ snapraid_compile_dir }}/build.sh"
    mode: a+x

- name: Change to snapraid install dir and run build script
  shell: 
    cmd: ./build.sh
    chdir: "{{ snapraid_compile_dir }}"

- name: Install a .deb package from the internet
  become: true
  apt:
    deb: "{{ snapraid_compile_dir }}/build/snapraid-from-source.deb"
    state: present

- name: Schedule parity cheks as admin
  become: true
  cron:
    name: "Sync parity"
    minute: "0"
    hour: "5"
    job: "snapraid -c {{ snapraid_conf_dir }}/snapraid.conf sync"
    user: root