- name: Install kernel modules
  apt:
    name:
      - linux-modules-extra-{{ ansible_kernel }}
      - linux-headers-{{ ansible_kernel }}
    state: latest
  register: kernel_modules_install

- name: Reboot the system if kernel modules were installed
  reboot:
  when: kernel_modules_install is changed

- name: Load nvme_tcp module
  modprobe:
    name: nvme_tcp
    state: present
    persistent: present

- name: Verify nvme_tcp module is loaded
  shell: "lsmod | grep nvme_tcp"
  register: nvme_tcp_status
  ignore_errors: true

- name: Display nvme_tcp module status
  debug:
    msg: "nvme_tcp module is {{ 'loaded' if nvme_tcp_status.rc == 0 else 'not loaded' }}"
