- hosts: all_servers
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: update all packages
      become: true
      package:
        name: '*'
        state: latest
        autoremove: true

- name: Reboot non-critical machines after upgrades
  hosts:
    - utilities
    - media_server
    - k3s_cluster
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      become: true
      reboot:
      when: reboot_required_file.stat.exists == true
