- name: Reboot all nodes in k3s_cluster
  hosts: k3s_cluster
  vars_files:
    - ../vars/vault.yml
  become: true
  tasks:
    - name: Reboot the machine
      ansible.builtin.command:
        cmd: reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for the machines to come back online
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
