- hosts: nfs_server
#  tags:
  #  - fs
  vars_files:
    - ../vars/vault.yml
  roles:
    - filesystem
    - docker

- hosts: nfs_client
  tags:
    - fs
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: install nfs-utils
      become: true
      apt: 
        name: nfs-common
        state: latest
    
    - name: create install directory
      become: true
      file:
        path: "{{ storage_dir }}"
        state: directory

    - name: Bind storage to nfs exports
      become: true
      ansible.posix.mount:
        state: mounted
        path: "{{ storage_dir }}"
        src: "192.168.0.103:/"
        fstype: nfs
        opts: soft,nolock

- hosts: 
    - media_server
    - utilities
  tags:
    - applications
  vars_files:
    - ../vars/vault.yml
  roles:
    - docker

- hosts: all_servers
  tags:
    - general
  vars_files:
    - ../vars/vault.yml
  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
    - role: general_setup
