- name: Base configuration
  hosts: all_servers
  tags:
    - general
  vars_files:
    - ../vars/vault.yml
  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
    - role: general_setup

- name: Inital docker setup
  hosts: docker
  vars_files:
    - ../vars/vault.yml
  roles:
    - install-docker
    - role: load_usb_modules
      when: 
        - docker_templates is defined
        - "'home-assistant' in docker_templates"
      become: true

- name: Ensure nvme_tcp module and multipath is configured
  vars_files:
    - ../vars/vault.yml
  hosts: node
  become: true
  roles:
    - kubernetes

- name: Developer machine setup
  hosts: developer
  become: true
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Fetch Kubernetes config from first master node
      ansible.builtin.fetch:
        src: "/home/{{ hostvars[groups['master'][0]]['ansible_user'] }}/.kube/config"
        dest: "/home/{{ ansible_user }}/.kube/config"
        flat: yes
      delegate_to: "{{ groups['master'][0] }}"
      become: false

    - name: Set permissions on Kubernetes config
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/config"
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

- name: Mount NFS shares
  hosts: nfs_client
  become: true
  vars_files:
    - ../vars/vault.yml
  vars:
    nfs_mount_point: "{{ storage_dir }}"
    nfs_mount_src: "storage.local.hejsan.xyz:/"
  roles:
    - nfs_share