- hosts: 
    - media_server
    - utilities
  tags:
    - applications
  vars_files:
    - ../vars/vault.yml
  roles:
    - docker

- hosts: all_servers
  tags:
    - general
  vars_files:
    - ../vars/vault.yml
  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
    - role: general_setup
