- hosts: storage
  vars_files:
    - ../vars/vault.yml
  roles:
    - filesystem

- hosts: nfs_server
  vars_files:
    - ../vars/vault.yml
  roles:
    - docker
  tasks:
      - name: Load kernel modules for NFS
        become: true
        modprobe:
          name: "{{ item }}"
        loop:
          - nfsd
          - nfs

- hosts: nfs_client
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: install nfs-utils
      become: true
      apt: 
        name: nfs-common
        state: latest
    
    - name: create install directory
      become: true
      file:
        path: "/mnt/nfs"
        state: directory

    - name: Bind storage to nfs exports
      become: true
      ansible.posix.mount:
        state: mounted
        path: "/mnt/nfs"
        src: "192.168.0.102:/"
        fstype: nfs
        opts: soft,nolock

- name: Mount default storage dir as smb share
  hosts: smb_client
  become: true
  vars_files:
    - ../vars/vault.yml

  vars:
    smb_share_username: "alice"
    smb_share_password: "alipass"
    smb_share_path: "//192.168.0.102/alice"
    mount_point: "{{ storage_dir }}"
    mount_gid: "{{ main_gid }}"
    mount_uid: "{{ main_uid }}"
    credentials_file: "cifs_credentials_file"

  roles:
  - smb_share

- name: Mount smb share for lancache
  hosts: smb_client
  become: true
  vars_files:
    - ../vars/vault.yml

  vars:
    smb_share_username: "alice"
    smb_share_password: "alipass"
    smb_share_path: "//192.168.0.102/alice/cache"
    mount_point: "/mnt/cache"
    mount_gid: "33" #www-data
    mount_uid: "33"  #www-data
    credentials_file: "cifs_credentials_file"

  roles:
  - smb_share