- name: Mount drives
  hosts: storage
  vars_files:
    - ../vars/vault.yml
  roles:
    - filesystem

- name: Deploy netowork shares
  hosts: network_storage
  become: true
  vars_files:
    - ../vars/vault.yml
  roles:
    - geerlingguy.samba
    - geerlingguy.nfs
  tasks:
    - name: Add Samba shares to smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        block: "{{ item.content }}"
        insertafter: EOF
      loop: "{{ smb_exports }}"

    - name: Restart Samba service
      service:
        name: smbd
        state: restarted

- name: Mount NFS shares
  hosts: nfs_client
  become: true
  vars_files:
    - ../vars/vault.yml
  vars:
    nfs_mount_point: "{{ storage_dir }}"
    nfs_mount_src: "storage.local.hejsan.xyz:/"
  roles:
    - nfs_share

- name: Mount SMB share
  hosts: smb_client
  become: true
  vars_files:
    - ../vars/vault.yml
  vars:
    smb_share_path: "//storage.local.hejsan.xyz/public"
    mount_point: "/mnt/smb"
    mount_gid: "{{ main_gid }}"
    mount_uid: "{{ main_uid }}"
  roles:
    - smb_share
