- name: Mount drives
  hosts: storage
  vars_files:
    - ../vars/vault.yml
  roles:
    - filesystem

- name: Deploy netowork shares
  hosts: network_storage
  become: true
  vars_files:
    - ../vars/vault.yml
  roles:
    - docker-templates
    - geerlingguy.nfs

- name: Mount NFS shares
  hosts: nfs_client
  become: true
  vars_files:
    - ../vars/vault.yml
  vars:
    nfs_mount_point: "{{ storage_dir }}"
    nfs_mount_src: "storage.local.hejsan.xyz:/"
  roles:
    - nfs_share

- name: Mount SMB share
  hosts: smb_client
  become: true
  vars_files:
    - ../vars/vault.yml
  vars:
    smb_share_username: "alice"
    smb_share_password: "alipass"
    smb_share_path: "//storage.local.hejsan.xyz/alice"
    mount_point: "/mnt/smb"
    mount_gid: "{{ main_gid }}"
    mount_uid: "{{ main_uid }}"
    credentials_file: "cifs_credentials_file"
  roles:
    - smb_share
