---
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-htpasswd
data:
  htpasswd: |-
    Replace with $ htpasswd -Bbn username password

---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-config
data:
  config.yml: |-
    proxy:
      remoteurl: https://registry-1.docker.io
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-env
data:
  REGISTRY_AUTH: htpasswd
  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    
    