apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/cert-manager
  - ../../bases/actions-runner-controller
  
 #Copy from base
patches:
  - secret-cf-token.yaml
  - secret-runner-token.yaml
