---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lundbergjonas96@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: lundbergjonas96@gmail.com
            apiTokenSecretRef:
              name: cloudflare
              key: hejsan-xyz-edit
        selector:
          dnsZones:
            - "hejsan.xyz"
