- name: Get all devices
  command: lsblk -o NAME,UUID,FSTYPE,SIZE --json
  register: all_devices

- name: Create list of all available partitions
  set_fact:
    child_devices: "{{ child_devices | default([]) + item.children }}"
  loop: "{{ (all_devices.stdout | from_json).blockdevices }}"
  when:
    - item.children is defined
    - item.children | list | length == 1

- name: Print all devices
  debug:
    msg: "{{ child_devices }}"

- name: Initilize list of non-LUKS partitions
  set_fact:
    non_luks_partitions: "{{ [] }}"

- name: Create list of non-LUKS partitions
  set_fact:
    non_luks_partitions: "{{ non_luks_partitions | default([]) + [{
      'name': item.name,
      'fstype': item.fstype,
      'size': item.size,
      'src': '/dev/' ~ item.name,
      'uuid': item.uuid
      }] }}"
  loop: "{{ child_devices }}"
  when:
    - item.fstype != 'crypto_LUKS'

- name: Initilize list of LUKS partitions
  set_fact:
    luks_partitions: "{{ [] }}"

- name: Create list of LUKS partitions and their children
  set_fact:
    luks_partitions: "{{ luks_partitions | default([]) + [{
      'name': item.children[0].name,
      'fstype': item.children[0].fstype,
      'size': item.children[0].size,
      'src': '/dev/mapper/' ~ item.children[0].name,
      'uuid': item.children[0].uuid
      }] }}"
  loop: "{{ child_devices }}"
  when:
    - item.children is defined
    - item.fstype == 'crypto_LUKS'
    - item.children is defined
    - item.children | length == 1

- name: Debug non-LUKS partitions
  debug:
    msg: "Non-LUKS partitions: {{ non_luks_partitions }}"

- name: Debug LUKS partitions
  debug:
    msg: "LUKS partitions: {{ luks_partitions }}"

- name: Add non-LUKS partitions to /etc/fstab
  become: true
  ansible.posix.mount:
    state: mounted
    path: "/mnt/drives/{{ crypttab_name_prefix }}_{{ item.uuid.split('-')[0] }}"
    src: "/dev/disk/by-uuid/{{ item.uuid }}"
    fstype: "{{ item.fstype }}"
  loop: "{{ non_luks_partitions }}"

- name: Add LUKS partitions to /etc/fstab
  become: true
  ansible.posix.mount:
    state: mounted
    path: "/mnt/drives/{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
  loop: "{{ luks_partitions }}"
