---
galaxy_info:
  author: your_name
  description: Install and configure Obico server using Docker Compose
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
