---
# Network Storage Configuration
# ==========================

# Service Templates
services:
  templates:
    - copyparty
    # - nfs

# NFS Configuration
nfs:
  share_root: /srv/storage
  exports:
    - share: "{{ docker.dirs.storage }}"
      options: "*(rw,sync,fsid=0,crossmnt,no_subtree_check,anonuid={{ user.uid }},anongid={{ user.gid }})"

# Samba Configuration
samba:
  shares:
    - name: public
      config: |
        [public]
        path = {{ paths.storage }}
        public = yes
        guest only = yes
        writable = yes
        force create mode = 0666
        force directory mode = 0777
        browseable = yes

# Maintenance Schedule
maintenance:
  schedule: "*-*-01 03:00:00"
