- name: Install docker
  become: true
  apt:
    name: docker
    state: present

- name: Install docker compose
  become: true
  apt:
    name: docker-compose
    state: present

- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to group
  become: true
  user:
    name: "{{ main_username }}"
    groups:
      - docker
    append: yes

- name: Start and Enable docker
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon-reload: yes

- name: Log into private registry and force re-authorization
  community.docker.docker_login:
    registry_url: "{{ docker_registry_domain }}"
    username: "{{ docker_registry_user }}"
    password: "{{ docker_registry_password }}"
    reauthorize: true
    validate_certs: true

- name: Create docker template directory
  become: true
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Find all docker templates
  find:
    paths: "{{ docker_compose_dir }}"
    patterns: "*.yml"
  register: existing_docker_templates

- name: Delete all existing templates
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ existing_docker_templates['files'] }}"

- name: Deploy compose templates
  become: true
  template:
    src: ../templates/compose/{{ item }}.yml
    dest: "{{ docker_compose_dir }}/{{ item }}.yml"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "0640"
  loop: "{{ docker_templates }}"


- name: Create docker script directory
  become: true
  file:
    path: "{{ script_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Deploy scripts
  become: true
  template:
    src: ../templates/scripts/{{ item }}.sh
    dest: "{{ script_dir }}/{{ item }}.sh"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "0740"
  loop: "{{ script_templates }}"

- name: Start containers
  command: "{{ script_dir }}/start.sh"
