- name: Deploy service templates
  become: true
  template:
    src: ../templates/timers/{{ item }}.service.j2
    dest: "{{ timer_dir }}/{{ item }}.service"
  loop: "{{ timers }}"

- name: Deploy timer templates
  become: true
  template:
    src: ../templates/timers/{{ item }}.timer.j2
    dest: "{{ timer_dir }}/{{ item }}.timer"
  loop: "{{ timers }}" 
  when: maintenance_calendar is defined

- name: Enable timer
  become: true
  systemd:
    name: "{{ item }}.timer"
    enabled: yes
    state: started
    daemon-reload: yes
  loop: "{{ timers }}"
  when: maintenance_calendar is defined

- name: Disable timer if no calendar
  become: true
  systemd:
    name: "{{ item }}.timer"
    enabled: no
    state: started
    daemon-reload: yes
  loop: "{{ timers }}"
  when: maintenance_calendar is undefined


