- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present

- name: Create docker template directory
  become: true
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Deploy compose templates
  become: true
  template:
    src: ../templates/{{ item }}.yml
    dest: "{{ docker_compose_dir }}/{{ item }}.yml"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: '0640'
  loop: "{{ docker_templates }}"


- name: Create docker script directory
  become: true
  file:
    path: "{{ script_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Deploy scripts
  become: true
  template:
    src: ../templates/scripts/{{ item }}.sh
    dest: "{{ script_dir }}/{{ item }}.sh"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: '0740'
  loop: "{{ script_templates }}"

