services:
  emby:
    image: {{ docker_registry_domain }}/linuxserver/emby
    container_name: emby
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/emby:/config"
      - "{{ docker_storage_dir }}/files/:{{ docker_storage_dir }}/files/"
    restart: always
