services:
  grafana:
    image: {{ docker_registry_domain }}/grafana/grafana:latest
    container_name: grafana
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/grafana:/var/lib/grafana"
    ports:
      - 3000:3000
    restart: always
