services:
  homeassistant:
    image: {{ docker_registry_domain }}/linuxserver/homeassistant:2024.10.1-ls32
    container_name: homeassistant
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/homeassistant:/config"
    ports:
      - 8123:8123
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  zwave:
    image: {{ docker_registry_domain }}/zwavejs/zwave-js-ui:9.16.4
    container_name: zwave
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
      - SESSION_SECRET=ccd3fc23c7e9dafc5e8b8fdd5a621dab
    volumes:
      - "{{ docker_data_dir }}/zwave:/usr/src/app/store"
    restart: always
    ports:
      - 8091:8091
      - 3000:3000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  node-red:
    image: {{ docker_registry_domain }}/nodered/node-red:4.0.2-22
    container_name: nodered
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - '{{ docker_data_dir }}/nodered/data:/data'
    ports:
      - '1880:1880'
