services:
  homeassistant:
    image: {{ docker_registry_domain }}/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/homeassistant:/config"
    ports:
      - 8123:8123
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  
