services:
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
      - "{{ docker_data_dir }}/midarr:/app/database"
      - "{{ movies_dir }}:{{ movies_dir }}"
      - "{{ series_dir }}:{{ series_dir }}"
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
#       App config
      - APP_URL=http://{{ docker_server_domain }}:4000

#       Admin account
      - SETUP_ADMIN_EMAIL={{ email }}
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=somepassword # minimum length 12

#       Radarr integration
      - RADARR_BASE_URL=http://{{ docker_server_domain }}:7878
      - RADARR_API_KEY={{ radarr_api_key }}

#       Sonarr integration
      - SONARR_BASE_URL=http://{{ docker_server_domain }}:8989
      - SONARR_API_KEY={{ sonarr_api_key}}