services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
      - NFS_DISABLE_VERSION_3=true
      - NFS_EXPORT_0={{ nfs_share }} *(fsid=0,rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=1000,anongid=1000)
      - NFS_EXPORT_1={{ nfs_share }}/files *(fsid=1,rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=1000,anongid=1000)
      - NFS_EXPORT_2={{ nfs_share }}/kubernetes *(fsid=2,rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=1000,anongid=1000)
      - NFS_EXPORT_3={{ nfs_share }}/cache *(fsid=2,rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=33,anongid=33)
    volumes:
      - "{{ docker_storage_dir }}:{{ nfs_share }}"
      - "/lib/modules:/lib/modules:ro"
    ports:
      - 2049:2049
    security_opt:
      - apparmor=erichough-nfs #https://github.com/ehough/docker-nfs-server/issues/5 sudo systemctl disable apparmor
    restart: always
