services:
  ombi:
    image: {{ docker_registry_domain }}/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/ombi:/config"
    restart: always
