services:
  swag:
    image: {{ docker_registry_domain }}/linuxserver/swag:latest
    container_name: swag
    environment:
      - EMAIL={{ email }}
      - URL=hejsan.xyz
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - "{{ docker_data_dir }}/swag:/config"
    ports:
      - 8081:80
      - 4433:443
      - 8085:81
    restart: always
