services:
  swag:
    image: {{ docker_registry_domain }}/linuxserver/swag:2024.10.1-ls32
    container_name: swag
    environment:
      - EMAIL={{ email }}
      - URL=hejsan.xyz
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/swag:/config"
    ports:
      - 8081:80
      - 4433:443
    restart: always
