services:
  unifi:
    image: "{{ docker_registry_domain }}/linuxserver/unifi-network-application:8.5.6-ls67"
    container_name: unifi
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
      - MONGO_DBNAME=unifi-db
      - MONGO_HOST=unifi-db
      - MONGO_PASS=pass
      - MONGO_PORT=27017
      - MONGO_USER=unifi
    depends_on:
      - unifi-db
    volumes:
      - "{{ docker_data_dir }}/unifi-network-application/config:/config"
    network_mode: host
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optioal
    restart: unless-stopped
  unifi-db:
    image: "{{ docker_registry_domain }}/library/mongo:7.0"
    container_name: unifi-db
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ docker_data_dir }}/unifi-network-application/db:/data/db"
      - "{{ docker_compose_dir }}/unifi-init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js" # Mount the script directly
    ports:
      - 27017:27017
    restart: unless-stopped

