services:
  unifi:
    image: "{{ docker_registry_domain }}/linuxserver/unifi-network-application"
    container_name: unifi
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
      - MONGO_DBNAME=unifi-db
      - MONGO_HOST=media.local.hejsan.xyz
      - MONGO_PASS=pass
      - MONGO_PORT=27017
      - MONGO_USER=unifi
    depends_on:
      unifi-db:
        condition: service_started
        required: true
    volumes:
      - "{{ docker_data_dir }}/unifi-network-application/config:/config"
    network_mode: host
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optioal
    restart: unless-stopped
  unifi-db:
    image: "{{ docker_registry_domain }}/mongo:7.0"
    container_name: unifi-db
    environment:
      - PUID={{ docker_puid }}
      - PGID={{ docker_pgid }}
      - TZ={{ timezone }}
    configs:
      - source: init-mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js
    volumes:
      - "{{ docker_data_dir }}/unifi-network-application/db:/data/db"
    ports:
      - 27017:27017
    restart: unless-stopped

configs:
  init-mongo.js:
    content: |
      db.getSiblingDB("unifi-db").createUser({user: "unifi", pwd: "pass", roles: [{role: "dbOwner", db: "unifi-db"}]}); 
      db.getSiblingDB("unifi-db_stat").createUser({user: "unifi", pwd: "pass", roles: [{role: "dbOwner", db: "unifi-db_stat"}]});