- name: Install necessary packages
  apt:
    name:
      - podman
      - pipx
    state: present

- name: Install Podman Compose via pipx
  community.general.pipx:
    name: podman-compose
    state: present

- name: Create docker template directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Create docker script directory
  file:
    path: "{{ docker_script_dir }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"

- name: Deploy scripts
  template:
    src: ../templates/scripts/{{ item }}.sh
    dest: "{{ docker_script_dir }}/{{ item }}.sh"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: "0740"
  loop: "{{ script_templates }}"
