version: "3.7"
services:
  cloudflare-ddns:
    container_name: cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY={{ cloudflare_api_key }}
      - ZONE={{ cloudflare_zone }}
      - PROXIED=true
