services:
  emby:
    image: {{ docker_registry_domain }}/linuxserver/emby
    container_name: emby
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/emby:/config"
      - "{{ storage_dir }}/files/:{{ storage_dir }}/files/"
    restart: always
