version: "3.7"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/jellyfin:/config"
      - "{{ storage_dir }}/files/:{{ storage_dir }}/files/"
    ports:
      - 8096:8096
    restart: always
