version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/plex:/config"
      - "{{ storage_dir }}/files/:{{ storage_dir }}/files/"
    restart: always
    network_mode: host
    
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/tautulli:/config"
      - "{{ appdata_path }}/plex/Library/Application Support/Plex Media Server/Logs/:/logs"
    ports:
      - 8181:8181
    restart: always
