version: "3.7"
services:
  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - "{{ appdata_path }}/tdarr/server:/app/server"
      - "{{ appdata_path }}/tdarr/configs:/app/configs"
      - "{{ appdata_path }}/tdarr/logs:/app/logs"
      - "{{ storage_dir }}/files/movies:/media/movies"
      - "{{ storage_dir }}/files/series:/media/tv"
      - "{{ storage_dir }}/files/transcode:/temp/transcode"
    ports:
      - 8265:8265
      - 8266:8266
    restart: always
  tdarr_node:
    image: haveagitgat/tdarr_node
    container_name: tdarr_node
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
      - nodeID=node1
      - nodeIP=tdarr_node
      - nodePort=8267
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - "{{ appdata_path }}/tdarr/configs:/app/configs"
      - "{{ appdata_path }}/tdarr/logs:/app/logs"
      - "{{ storage_dir }}/files/movies:/media/movies"
      - "{{ storage_dir }}/files/series:/media/tv"
      - "{{ storage_dir }}/files/transcode:/temp/transcode"
    ports:
      - 8267:8267
    restart: always
