version: "3.7"
services:
  unifi:
    image: {{ docker_registry_domain }}/linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ appdata_path }}/unifi:/config"
    network_mode: host
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
#      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optioal
    restart: always
