version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID={{ main_gid }}
      - GUID={{ main_uid }}
      - TZ={{ timezone }}
      - SERVERURL=wireguard.hejsan.xyz #optional
      - SERVERPORT=51888 #optional
      - PEERS=phone #optional
      - PEERDNS=1.1.1.1 #optional
     # - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - "{{ appdata_path }}wireguard/config:/config"
      - /lib/modules:/lib/modules
    ports:
      - 51888:51820/udp
    restart: unless-stopped