---
- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone Obico server repository
  git:
    repo: https://github.com/TheSpaghettiDetective/obico-server.git
    dest: "{{ obico_repo_dir }}"
    version: release
    update: yes

- name: Start Obico server with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ obico_repo_dir }}"

- name: Ensure Obico site is added for {{ inventory_hostname }} (or else it will always end up in a 500 error)
  command: docker compose run web ./manage.py site --add {{ inventory_hostname }}
  args:
    chdir: "{{ obico_repo_dir }}"
