- name: Install all packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
- name: generate SSH key "{{ ssh_key_filename }}"
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_filename }}"
    type: rsa
    size: 4096
    state: present
    force: no
- name: update all packages
  become: true
  package:
    name: '*'
    state: latest
    autoremove: true
