- name: Install all packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present

- name: generate SSH key "{{ ssh_key_filename }}"
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_filename }}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
- name: Set git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"