- hosts: localhost
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Install roles
      become: true
      command: ansible-galaxy install -r {{ role_path }}/../requirements.yml --ignore-errors
