- hosts: localhost
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: Install dependencies
      become: true
      command: ansible-galaxy install {{ item }}  -r {{ playbook_dir  }}/../requirements.yml --ignore-errors
      with_items:
        - roles
        - collections

