- hosts: nas
  tags:
    - fs
  vars_files:
    - ../vars/vault.yml
  roles:
    - filesystem

- hosts: media_server
  tags:
    - fs
  vars_files:
    - ../vars/vault.yml
  tasks:
    - name: install nfs-utils
      become: true
      pacman: 
        name: nfs-utils
        state: latest
    - name: create install directory
      become: true
      file:
        path: "{{ storage_dir }}"
        state: directory
    - name: Bind storage to nfs exports
      become: true
      ansible.posix.mount:
        state: mounted
        path: "{{ storage_dir }}/{{ item }}"
        src: "nas.localdomain:/{{ item }}"
        fstype: nfs
        opts: defaults,timeo=900,retrans=5,_netdev
      loop: "{{ exported_shares }}"



- hosts: media_server
  tags:
    - docker
  vars_files:
    - ../vars/vault.yml
  roles:
    - docker

- hosts: all_servers
  tags:
    - general
  vars_files:
    - ../vars/vault.yml
  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
    - role: general_setup
