- hosts: encrypted
  vars_files:
    - ../vars/vault.yml
  roles:
    - crypt_setup

- hosts: all_servers
  vars_files:
    - ../vars/vault.yml
  roles:
    - role: general_setup
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
