---
dependencies: []

galaxy_info:
  author: josmase
  description: Sets up local development environment for Ansible projects
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - development
    - local
    - git
    - ansible
    - setup