packages: 
  - fuse
  - libfuse2

merger_fs_version: 2.34.1
merger_fs_src: "https://github.com/trapexit/mergerfs/releases/download/{{ merger_fs_version }}/mergerfs_{{ merger_fs_version }}.ubuntu-focal_amd64.deb"


#merger_fs_mnt_opt: defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,dropcacheonclose=true,minfreespace=200G,fsname=mergerfs
merger_fs_mnt_opt: use_ino,cache.files=off,dropcacheonclose=true,allow_other,category.create=mfs
merger_fs_mnt_src: "{{ mount_dir }}/*"
# Default variables for filesystem_setup role

# Mount Configuration
storage:
  mount_base: /mnt/drives
  mount:
    options:
      default: "defaults,noatime"
      encrypted: "defaults,noatime,discard"

# Filesystem Settings
filesystem:
  type: xfs              # Default filesystem type
  options: "-L storage"  # Default mkfs options

# MergerFS Configuration
mergerfs:
  enabled: true
  mount_point: "{{ paths.storage }}"
  mount_options: "defaults,noatime,use_ino,allow_other,func.getattr=newest,category.create=mfs"

# SnapRAID Configuration
snapraid:
  enabled: false
  config_file: /etc/snapraid.conf
  data_disks: []      # List of data disks
  parity_disk: ""     # Parity disk location

snapraid_compile_dir: /opt/snapraid
snapraid_conf_dir: /opt/snapraid_conf

crypttab_name_prefix: automapped

