---
- name: Manage k3s runtime configuration (kubelet args)
  ansible.builtin.import_tasks: kubelet-config.yml
  tags:
    - kubelet
    - k3s_config

- name: Manage inotify sysctls
  ansible.builtin.import_tasks: sysctl-inotify.yml
  tags:
    - sysctl
    - tuning
