apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cors
  namespace: {{ .Release.Namespace | quote }}
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
      - DELETE
    accessControlAllowOriginList:
      -  https://{{ .Values.ui.domain }}
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true