- name: Install packages (Distribution-agnostic)
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Disable the BEEP (Zshrc - Common Task)
  ansible.builtin.lineinfile:
    line: unsetopt BEEP
    path: ~/.zshrc
    state: present
    create: yes
- name: Setup aliases (Zshrc - Common Task)
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "alias {{ item }}"
    state: present
    create: true
  loop:
    - rm="rm -v"
    - cp="cp -v"
    - mv="mv -v"